version: "3"

services:
  msg-db:
    image: simple-message/db:${TAG:-1.0}
    build:
      context: ./simple-message-db
    # ports:
    #   - 1433:1433
    env_file:
      - ./simple-message-db/.env
    volumes:
      - mssql:/var/opt/mssql

  msg-api:
    image: simple-message/api:${TAG:-1.0}
    build:
      context: ./simple-message-api
    ports:
      - 8000:80
    env_file:
      - ./simple-message-api/.env
    depends_on:
      - msg-db

  msg-ui:
    image: simple-message/ui:${TAG:-1.0}
    build:
      context: ./simple-message-ui
    ports:
      - 4000:4200
    depends_on:
      - msg-api

volumes: 
  mssql:
