version: "3"

services:
  db:
    image: simple-message/db:${TAG:-1.0}
    build:
      context: ./simple-message-db
      dockerfile: Dockerfile
    ports:
      - 1433:1433
    env_file: 
      - ./simple-message-db/.env

  api:
    image: simple-message/api:${TAG:-1.0}
    build:
      context: ./simple-message-api
      dockerfile: Dockerfile
    ports:
      - 8000:80

  ui:
    image: simple-message/ui:${TAG:-1.0}
    build: 
      context: ./simple-message-ui
      dockerfile: Dockerfile
    ports:
      - 4000:4200